import "./globals.css";

import Footer from "./components/Footer";
import type { Metadata } from "next";
import Navbar from "@/app/components/Navbar";
import { Nunito_Sans } from "next/font/google";

const nunitoSans = Nunito_Sans({
  // variable: "--font-nunito-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.className} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
